name: Bjørn Hembre
favicon: null
layout_spectrum: 0.96607
typography_spectrum: 0.94063
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#3f3f3f'
    - '#bebebe'
    - '#7f7f7f'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
