name: Bjørn Hembre
favicon: null
layout_spectrum: 1
typography_spectrum: 0.94063
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafafa'
    - '#000000'
    - '#d4d4d4'
    - '#676767'
    - '#c18c76'
  brandStrength: 0.3125
  lightness: 0.5625
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
