name: Bjørn Hembre
favicon: null
layout_spectrum: 0.02135
typography_spectrum: 0.59892
title: Brand and design consultancy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff0000'
    - '#bcbdbf'
    - '#ff7575'
    - '#ff9f9f'
  brandStrength: 0.9375
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
